Update to latest sensu-plugins version (2.5)
Some other plugins are starting to use newer versions of sensu-plugin,
which is resulting in the following error because this plugin also
ends up using 2.5:

Check failed to run: undefined method `parse' for
Sensu::Plugin::Metric::CLI::JSON:Class,
["/usr/local/bundle/bin/metrics-jenkins.rb:117:in `run'",
"/usr/local/bundle/gems/sensu-plugin-2.5.0/lib/sensu-plugin/cli.rb:57:in
`block in <class:CLI>'"]